### ISSUE TITLE
Library compatibility with LSM6DSR

### ISSUE THREAD

**Issue by TinManAkshay** [arduino-libraries/Arduino_LSM6DS3#15]
Hi,

I have got this LSM6DSR board https://www.digikey.com/en/products/detail/stmicroelectronics/STEVAL-MKI194V1/10078018.
So I wanted to know if this library can be used to extract the accelerometer values. OR this library is open-source can be modified according to the LSM6DSR?

Thanks,
Akshay

**Comment by per1234** [comment]
HI @TinManAkshay. This issue tracker is only used for reporting bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:
http://forum.arduino.cc/index.php?topic=148850
