### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by MeY0u** [arduino-libraries/Arduino_LSM6DS3#45]
Support for reading the temperature sensor (https://github.com/arduino-libraries/Arduino_LSM6DS3/pull/12) was added since the time of the last release.

It would be useful to make a new release to distribute this advancement to the library users.

**Comment by MeY0u** [comment]
indid i had to manually modify the arduino lib with the new release

**Comment by facchinm** [comment]
1.0.3 released with the new API
