### ISSUE TITLE
Access on-chip temperature sensor

### ISSUE THREAD

**Issue by woolseyj** [arduino-libraries/Arduino_LSM6DS3#9]
Requesting an enhancement to include access to the on-chip temperature sensor available on the LSM6DS3 device which can be accessed from the OUT_TEMP_L (0x20) and OUT_TEMP_H (0x21) registers.

**Comment by iLikePieTM** [comment]
Hey @woolseyj, I just added a pull request with temperature sensor support: #12

**Comment by woolseyj** [comment]
That is great, thank you.
